@baseUrl = http://localhost:5010 
@xAuthAccess = dXNlci1zdGlja3lfc2VjcmV0XzEyMzQ1Njc
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJuYW1lIjoicGVwZSIsImlkIjoxfSwicGVybWlzc2lvbnMiOlt7ImlkIjoxLCJuYW1lIjoicGVybWlzbyAxLjEifSx7ImlkIjoyLCJuYW1lIjoicGVybWlzbyAxLjIifSx7ImlkIjozLCJuYW1lIjoicGVybWlzbyAxLjMifV0sImlhdCI6MTc3MDQxNDEyMSwiZXhwIjoxNzcwNDE3NzIxfQ.LYfuP-KkA7J8Wd0gutz-b_3djyg2T03bVKiMbnnlJYI

##############

POST {{baseUrl}}/api/v1/sign-in
Content-Type: application/json
Accept: application/json
X-Auth-Trigger: {{xAuthAccess}}

{
  "user": {
    "username": "pepe",
    "id": 1
  },
  "roles": [
  {
    "id": 1,
    "name": "file-manager",
    "permissions": [
      { "id": 1, "name": "permiso 1.1" },
      { "id": 2, "name": "permiso 1.2" },
      { "id": 3, "name": "permiso 1.3" }
    ]
  }
]
}
##########

POST {{baseUrl}}/api/v1/sign-in
Content-Type: application/json
Accept: application/json
X-Auth-Trigger: {{xAuthAccess}}

{
  "user": {
    "username": "pepe",
    "id": 1
  },
  "roles": [
  {
    "id": 1,
    "name": "file-managers",
    "permissions": [
      { "id": 1, "name": "permiso 1.1" },
      { "id": 2, "name": "permiso 1.2" },
      { "id": 3, "name": "permiso 1.3" }
    ]
  }
]
}

##############

POST {{baseUrl}}/api/v1/sign-in
Content-Type: application/json
Accept: application/json
X-Auth-Trigger: asdfdsf

{
  "user": {
    "username": "pepe",
    "id": 1
  },
  "roles": [
  {
    "id": 1,
    "name": "file-manager",
    "permissions": [
      { "id": 1, "name": "permiso 1.1" },
      { "id": 2, "name": "permiso 1.2" },
      { "id": 3, "name": "permiso 1.3" }
    ]
  }
]
}

##############
GET {{baseUrl}}/api/v1/token/translate
Accept: application/json
X-Auth-Trigger: {{xAuthAccess}}
Authorization: Bearer {{jwt}}
